// <auto-generated />
namespace skn_curtain_Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201803041943138_add_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
